
name: Lighthouse CI
# Controls when the workflow will run
# Triggers the workflow on push 

on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            https://sandboxshoesandsox.mybigcommerce.com/
            https://sandboxshoesandsox.mybigcommerce.com/girls/
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage

